services:
  backend:
    build: ./back
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    depends_on:
      - db  
  front:
    build: ./frontend
    container_name: front
    ports:
      - "5173:80"
    depends_on:
      - backend 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blood
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
